// Editorial Tech Marketplace: customer-facing copy for Nexa's electronics affiliate storefront.
import type { LanguageCode } from "@/lib/i18n";

export type StoreCopy = {
  nav: { shop: string; phones: string; accessories: string; guides: string; contact: string; language: string };
  hero: { eyebrow: string; title: string; accent: string; body: string; primary: string; secondary: string; note: string };
  categories: { label: string; title: string; items: Array<{ number: string; title: string; description: string }> };
  essentials: { label: string; title: string; body: string; cards: Array<{ title: string; description: string; tag: string }> };
  approach: { label: string; title: string; body: string; points: string[]; action: string };
  guide: { label: string; title: string; body: string; action: string };
  footer: { tagline: string; shop: string; company: string; legal: string; privacy: string; terms: string; cookies: string; rights: string };
};

export const storeCopy: Record<LanguageCode, StoreCopy> = {
  en: {
    nav: { shop: "Shop", phones: "Phones", accessories: "Accessories", guides: "Guides", contact: "Contact", language: "Language" },
    hero: { eyebrow: "Electronics, selected for real life", title: "Your phone,", accent: "better supported.", body: "Find practical phone accessories and everyday electronics that keep power moving, protect what matters, and make daily tech easier to use.", primary: "Explore phone essentials", secondary: "How we select", note: "Independent category guides. Product links are added only when a recommendation is ready." },
    categories: { label: "Shop the edit", title: "Start with the way you use your phone.", items: [{ number: "01", title: "Smartphones", description: "The right device for work, play, and everything in between." }, { number: "02", title: "Power & charging", description: "Chargers, cables, and portable energy that keep up." }, { number: "03", title: "Protection", description: "Cases and screen care built for everyday movement." }, { number: "04", title: "Audio", description: "Portable sound and calls without unnecessary complexity." }, { number: "05", title: "Work & travel", description: "Small tools that make your phone work harder, anywhere." }] },
    essentials: { label: "Phone essentials", title: "Small upgrades. Clearer daily use.", body: "Begin with the accessories that solve the recurring problems around a phone — low battery, cable clutter, fragile screens, and unreliable calls.", cards: [{ title: "Power that travels", description: "Portable charging for long days away from the outlet.", tag: "Battery" }, { title: "A cleaner charge", description: "Compact chargers and durable cables for everyday carry.", tag: "Charging" }, { title: "Protection that fits", description: "Protective layers for screens, cameras, and cases.", tag: "Care" }, { title: "Sound without friction", description: "Simple audio accessories for calls, focus, and travel.", tag: "Audio" }] },
    approach: { label: "How Nexa curates", title: "Useful technology, not an endless catalogue.", body: "We organize recommendations by the job a product needs to do, so you can compare the category before you leave for a merchant site.", points: ["Everyday utility first", "Clear category context", "No invented ratings or discounts"], action: "Browse the category index" },
    guide: { label: "Before you buy", title: "Choose for your routine, not the spec sheet.", body: "Use our category guides to match power, protection, audio, and connectivity with the way you actually move through a day.", action: "Read the buying guides" },
    footer: { tagline: "Practical electronics for better everyday phone use.", shop: "Shop", company: "Nexa", legal: "Legal", privacy: "Privacy", terms: "Terms", cookies: "Cookies", rights: "All rights reserved." },
  },
  ar: {
    nav: { shop: "تسوّق", phones: "الهواتف", accessories: "الملحقات", guides: "الأدلة", contact: "تواصل", language: "اللغة" },
    hero: { eyebrow: "إلكترونيات مختارة للحياة اليومية", title: "هاتفك،", accent: "مدعوم بشكل أفضل.", body: "اكتشف ملحقات هواتف وإلكترونيات عملية تحافظ على الطاقة، وتحمي ما يهمك، وتجعل استخدام التقنية اليومي أسهل.", primary: "استكشف أساسيات الهاتف", secondary: "كيف نختار", note: "أدلة فئات مستقلة. لا تُضاف روابط المنتجات إلا عندما تصبح التوصية جاهزة." },
    categories: { label: "تسوّق الاختيارات", title: "ابدأ بالطريقة التي تستخدم بها هاتفك.", items: [{ number: "01", title: "الهواتف الذكية", description: "الجهاز المناسب للعمل والترفيه وكل ما بينهما." }, { number: "02", title: "الطاقة والشحن", description: "شواحن وكابلات وطاقة محمولة تواكب يومك." }, { number: "03", title: "الحماية", description: "أغطية وعناية بالشاشة مصممة للحركة اليومية." }, { number: "04", title: "الصوت", description: "صوت ومكالمات محمولة بلا تعقيد غير ضروري." }, { number: "05", title: "العمل والسفر", description: "أدوات صغيرة تجعل هاتفك أكثر فاعلية في كل مكان." }] },
    essentials: { label: "أساسيات الهاتف", title: "تحديثات صغيرة. استخدام يومي أوضح.", body: "ابدأ بالملحقات التي تحل المشكلات المتكررة حول الهاتف: البطارية المنخفضة، وفوضى الكابلات، والشاشات الهشة، والمكالمات غير الموثوقة.", cards: [{ title: "طاقة ترافقك", description: "شحن محمول للأيام الطويلة بعيداً عن المقبس.", tag: "بطارية" }, { title: "شحن أنظف", description: "شواحن صغيرة وكابلات متينة للحمل اليومي.", tag: "شحن" }, { title: "حماية مناسبة", description: "طبقات حماية للشاشة والكاميرا والغطاء.", tag: "عناية" }, { title: "صوت بلا احتكاك", description: "ملحقات صوت بسيطة للمكالمات والتركيز والسفر.", tag: "صوت" }] },
    approach: { label: "كيف تختار Nexa", title: "تقنية مفيدة، لا كتالوج لا ينتهي.", body: "ننظم التوصيات حسب المهمة التي يجب أن ينجزها المنتج، لتقارن الفئة بوضوح قبل الانتقال إلى موقع التاجر.", points: ["الفائدة اليومية أولاً", "سياق واضح للفئة", "لا تقييمات أو خصومات مختلقة"], action: "تصفح فهرس الفئات" },
    guide: { label: "قبل الشراء", title: "اختر وفق روتينك، لا وفق ورقة المواصفات.", body: "استخدم أدلة الفئات لمطابقة الطاقة والحماية والصوت والاتصال مع الطريقة التي تعيش بها يومك فعلياً.", action: "اقرأ أدلة الشراء" },
    footer: { tagline: "إلكترونيات عملية لاستخدام يومي أفضل للهاتف.", shop: "تسوّق", company: "Nexa", legal: "قانوني", privacy: "الخصوصية", terms: "الشروط", cookies: "ملفات الارتباط", rights: "جميع الحقوق محفوظة." },
  },
  es: {
    nav: { shop: "Comprar", phones: "Teléfonos", accessories: "Accesorios", guides: "Guías", contact: "Contacto", language: "Idioma" },
    hero: { eyebrow: "Electrónica elegida para la vida real", title: "Tu teléfono,", accent: "mejor acompañado.", body: "Descubre accesorios de teléfono y electrónica práctica que mantienen la energía, protegen lo importante y facilitan el uso diario.", primary: "Explorar esenciales", secondary: "Cómo elegimos", note: "Guías de categoría independientes. Los enlaces se agregan cuando una recomendación está lista." },
    categories: { label: "Explora la selección", title: "Empieza por cómo usas tu teléfono.", items: [{ number: "01", title: "Smartphones", description: "El dispositivo adecuado para trabajo, ocio y más." }, { number: "02", title: "Energía y carga", description: "Cargadores, cables y energía portátil para tu ritmo." }, { number: "03", title: "Protección", description: "Fundas y cuidado de pantalla para el movimiento diario." }, { number: "04", title: "Audio", description: "Sonido y llamadas portátiles sin complejidad." }, { number: "05", title: "Trabajo y viajes", description: "Pequeñas herramientas para usar mejor el teléfono." }] },
    essentials: { label: "Esenciales del teléfono", title: "Pequeñas mejoras. Uso diario más claro.", body: "Empieza con accesorios que resuelven batería baja, cables desordenados, pantallas frágiles y llamadas poco fiables.", cards: [{ title: "Energía para viajar", description: "Carga portátil para días lejos del enchufe.", tag: "Batería" }, { title: "Carga más limpia", description: "Cargadores compactos y cables duraderos.", tag: "Carga" }, { title: "Protección adecuada", description: "Capas de protección para pantalla, cámara y funda.", tag: "Cuidado" }, { title: "Sonido sin fricción", description: "Audio simple para llamadas, foco y viajes.", tag: "Audio" }] },
    approach: { label: "Cómo selecciona Nexa", title: "Tecnología útil, no un catálogo infinito.", body: "Organizamos recomendaciones según la función que un producto debe cumplir.", points: ["Utilidad diaria primero", "Contexto claro", "Sin valoraciones ni descuentos inventados"], action: "Ver el índice" },
    guide: { label: "Antes de comprar", title: "Elige para tu rutina, no para la ficha técnica.", body: "Usa las guías para relacionar energía, protección, audio y conectividad con tu día.", action: "Leer guías" },
    footer: { tagline: "Electrónica práctica para un mejor uso diario del teléfono.", shop: "Comprar", company: "Nexa", legal: "Legal", privacy: "Privacidad", terms: "Términos", cookies: "Cookies", rights: "Todos los derechos reservados." },
  },
  fr: {
    nav: { shop: "Boutique", phones: "Téléphones", accessories: "Accessoires", guides: "Guides", contact: "Contact", language: "Langue" },
    hero: { eyebrow: "L'électronique choisie pour le quotidien", title: "Votre téléphone,", accent: "mieux accompagné.", body: "Découvrez des accessoires téléphone et de l'électronique pratique qui préservent l'énergie, protègent l'essentiel et simplifient le quotidien.", primary: "Explorer les essentiels", secondary: "Notre sélection", note: "Guides de catégories indépendants. Les liens sont ajoutés lorsqu'une recommandation est prête." },
    categories: { label: "Explorer la sélection", title: "Commencez par votre usage du téléphone.", items: [{ number: "01", title: "Smartphones", description: "Le bon appareil pour le travail et les loisirs." }, { number: "02", title: "Énergie et charge", description: "Chargeurs, câbles et énergie mobile." }, { number: "03", title: "Protection", description: "Coques et soin d'écran pour le quotidien." }, { number: "04", title: "Audio", description: "Son et appels portables sans complexité." }, { number: "05", title: "Travail et voyage", description: "Des outils compacts pour aller plus loin." }] },
    essentials: { label: "Essentiels téléphone", title: "Petites améliorations. Usage plus clair.", body: "Commencez avec les accessoires qui répondent aux problèmes récurrents du téléphone.", cards: [{ title: "Énergie mobile", description: "Une charge portable pour les longues journées.", tag: "Batterie" }, { title: "Charge nette", description: "Chargeurs compacts et câbles durables.", tag: "Charge" }, { title: "Protection ajustée", description: "Protection pour écran, caméra et coque.", tag: "Soin" }, { title: "Son simple", description: "Audio pour appels, concentration et voyage.", tag: "Audio" }] },
    approach: { label: "La sélection Nexa", title: "De la technologie utile, pas un catalogue sans fin.", body: "Nous organisons les recommandations selon le besoin réel du produit.", points: ["Utilité d'abord", "Contexte clair", "Aucune note ou remise inventée"], action: "Voir les catégories" },
    guide: { label: "Avant l'achat", title: "Choisissez pour votre routine, pas pour la fiche technique.", body: "Utilisez les guides pour associer énergie, protection, audio et connectivité à votre journée.", action: "Lire les guides" },
    footer: { tagline: "Une électronique pratique pour mieux utiliser son téléphone.", shop: "Boutique", company: "Nexa", legal: "Légal", privacy: "Confidentialité", terms: "Conditions", cookies: "Cookies", rights: "Tous droits réservés." },
  },
  de: {
    nav: { shop: "Shop", phones: "Telefone", accessories: "Zubehör", guides: "Ratgeber", contact: "Kontakt", language: "Sprache" },
    hero: { eyebrow: "Elektronik für den echten Alltag", title: "Ihr Telefon,", accent: "besser unterstützt.", body: "Entdecken Sie praktisches Telefonzubehör und Elektronik, die Energie verfügbar hält, Wichtiges schützt und den Alltag vereinfacht.", primary: "Essentials entdecken", secondary: "Unsere Auswahl", note: "Unabhängige Kategorien. Links werden ergänzt, sobald eine Empfehlung bereit ist." },
    categories: { label: "Auswahl entdecken", title: "Beginnen Sie mit Ihrer Telefonnutzung.", items: [{ number: "01", title: "Smartphones", description: "Das passende Gerät für Arbeit und Freizeit." }, { number: "02", title: "Strom und Laden", description: "Ladegeräte, Kabel und mobile Energie." }, { number: "03", title: "Schutz", description: "Hüllen und Displayschutz für jeden Tag." }, { number: "04", title: "Audio", description: "Mobiler Klang und Anrufe ohne Komplexität." }, { number: "05", title: "Arbeit und Reise", description: "Kleine Werkzeuge für mehr Möglichkeiten." }] },
    essentials: { label: "Telefon-Essentials", title: "Kleine Upgrades. Klarerer Alltag.", body: "Starten Sie mit Zubehör für Akku, Kabel, Schutz und Anrufe.", cards: [{ title: "Energie unterwegs", description: "Mobile Ladung für lange Tage.", tag: "Akku" }, { title: "Sauber laden", description: "Kompakte Ladegeräte und langlebige Kabel.", tag: "Laden" }, { title: "Passender Schutz", description: "Schutz für Display, Kamera und Hülle.", tag: "Pflege" }, { title: "Klarer Klang", description: "Audio für Anrufe, Fokus und Reise.", tag: "Audio" }] },
    approach: { label: "Nexa wählt aus", title: "Nützliche Technik, kein endloser Katalog.", body: "Wir ordnen Empfehlungen nach der Aufgabe eines Produkts.", points: ["Alltagsnutzen zuerst", "Klarer Kontext", "Keine erfundenen Bewertungen oder Rabatte"], action: "Kategorien ansehen" },
    guide: { label: "Vor dem Kauf", title: "Wählen Sie für Ihre Routine, nicht für das Datenblatt.", body: "Nutzen Sie die Ratgeber für Energie, Schutz, Audio und Konnektivität.", action: "Ratgeber lesen" },
    footer: { tagline: "Praktische Elektronik für bessere Telefonnutzung.", shop: "Shop", company: "Nexa", legal: "Rechtliches", privacy: "Datenschutz", terms: "Bedingungen", cookies: "Cookies", rights: "Alle Rechte vorbehalten." },
  },
  pt: {
    nav: { shop: "Loja", phones: "Telefones", accessories: "Acessórios", guides: "Guias", contact: "Contato", language: "Idioma" },
    hero: { eyebrow: "Eletrônicos escolhidos para a vida real", title: "Seu telefone,", accent: "melhor acompanhado.", body: "Encontre acessórios de telefone e eletrônicos práticos que mantêm a energia, protegem o essencial e facilitam a tecnologia do dia a dia.", primary: "Explorar essenciais", secondary: "Como selecionamos", note: "Guias independentes. Links são adicionados quando uma recomendação está pronta." },
    categories: { label: "Explore a seleção", title: "Comece pela forma como usa seu telefone.", items: [{ number: "01", title: "Smartphones", description: "O dispositivo certo para trabalho e lazer." }, { number: "02", title: "Energia e carga", description: "Carregadores, cabos e energia portátil." }, { number: "03", title: "Proteção", description: "Capas e cuidado de tela para o dia a dia." }, { number: "04", title: "Áudio", description: "Som e chamadas sem complexidade." }, { number: "05", title: "Trabalho e viagem", description: "Ferramentas compactas para usar em qualquer lugar." }] },
    essentials: { label: "Essenciais do telefone", title: "Pequenos upgrades. Uso diário mais claro.", body: "Comece com acessórios para bateria baixa, cabos, telas frágeis e chamadas.", cards: [{ title: "Energia para viajar", description: "Carga portátil para dias longos.", tag: "Bateria" }, { title: "Carga limpa", description: "Carregadores compactos e cabos duráveis.", tag: "Carga" }, { title: "Proteção certa", description: "Proteção para tela, câmera e capa.", tag: "Cuidado" }, { title: "Som simples", description: "Áudio para chamadas, foco e viagem.", tag: "Áudio" }] },
    approach: { label: "Como a Nexa seleciona", title: "Tecnologia útil, não um catálogo infinito.", body: "Organizamos recomendações pela função que o produto precisa cumprir.", points: ["Utilidade diária primeiro", "Contexto claro", "Sem avaliações ou descontos inventados"], action: "Ver categorias" },
    guide: { label: "Antes de comprar", title: "Escolha para sua rotina, não para a ficha técnica.", body: "Use os guias para conectar energia, proteção, áudio e conectividade ao seu dia.", action: "Ler guias" },
    footer: { tagline: "Eletrônicos práticos para melhor uso diário do telefone.", shop: "Loja", company: "Nexa", legal: "Legal", privacy: "Privacidade", terms: "Termos", cookies: "Cookies", rights: "Todos os direitos reservados." },
  },
  ja: {
    nav: { shop: "ショップ", phones: "スマートフォン", accessories: "アクセサリー", guides: "ガイド", contact: "お問い合わせ", language: "言語" },
    hero: { eyebrow: "毎日のために選んだエレクトロニクス", title: "あなたのスマートフォンを、", accent: "もっと快適に。", body: "電源を保ち、大切なものを守り、日常のテクノロジーを使いやすくする実用的なアクセサリーを見つけましょう。", primary: "スマホ必需品を見る", secondary: "選定基準を見る", note: "独立したカテゴリガイドです。推薦が準備でき次第、商品リンクを追加します。" },
    categories: { label: "セレクションを見る", title: "スマートフォンの使い方から始めましょう。", items: [{ number: "01", title: "スマートフォン", description: "仕事と日常に合うデバイス。" }, { number: "02", title: "電源と充電", description: "充電器、ケーブル、持ち運べる電力。" }, { number: "03", title: "保護", description: "日常の移動に対応するケースと画面ケア。" }, { number: "04", title: "オーディオ", description: "複雑さのない音声と通話。" }, { number: "05", title: "仕事と旅行", description: "どこでもスマホを活かす小さなツール。" }] },
    essentials: { label: "スマホの必需品", title: "小さな改善。より明確な毎日。", body: "バッテリー、ケーブル、画面、通話の悩みを解決するアクセサリーから始めます。", cards: [{ title: "持ち運べる電力", description: "コンセントから離れた長い日のために。", tag: "バッテリー" }, { title: "すっきり充電", description: "コンパクトな充電器と耐久性のあるケーブル。", tag: "充電" }, { title: "適した保護", description: "画面、カメラ、ケースの保護。", tag: "ケア" }, { title: "手軽な音", description: "通話、集中、旅行のためのオーディオ。", tag: "オーディオ" }] },
    approach: { label: "Nexaの選定", title: "役立つ技術、終わりのないカタログではありません。", body: "製品が果たすべき役割でおすすめを整理します。", points: ["日常の有用性を優先", "明確なカテゴリ文脈", "架空の評価や割引はなし"], action: "カテゴリを見る" },
    guide: { label: "購入前に", title: "仕様表ではなく、日課に合わせて選ぶ。", body: "電源、保護、オーディオ、接続を日常の動きに合わせるガイドです。", action: "購入ガイドを読む" },
    footer: { tagline: "毎日のスマホ利用を良くする実用的なエレクトロニクス。", shop: "ショップ", company: "Nexa", legal: "法務", privacy: "プライバシー", terms: "利用規約", cookies: "Cookie", rights: "All rights reserved." },
  },
  zh: {
    nav: { shop: "选购", phones: "手机", accessories: "配件", guides: "指南", contact: "联系我们", language: "语言" },
    hero: { eyebrow: "为真实生活挑选的电子产品", title: "让你的手机，", accent: "得到更好支持。", body: "寻找实用的手机配件和日常电子产品，让电量持续、保护重要设备，并让每天的科技使用更轻松。", primary: "探索手机必需品", secondary: "了解我们的选择", note: "独立品类指南。准备好推荐后才会添加商品链接。" },
    categories: { label: "浏览精选", title: "从你使用手机的方式开始。", items: [{ number: "01", title: "智能手机", description: "适合工作、娱乐和日常使用的设备。" }, { number: "02", title: "电源与充电", description: "充电器、线缆和随身电源。" }, { number: "03", title: "保护", description: "适合日常移动的保护壳和屏幕护理。" }, { number: "04", title: "音频", description: "轻松实现便携音频和通话。" }, { number: "05", title: "工作与旅行", description: "让手机随时更高效的小工具。" }] },
    essentials: { label: "手机必需品", title: "小升级，更清晰的日常使用。", body: "从能解决低电量、线缆杂乱、屏幕易碎和通话不稳问题的配件开始。", cards: [{ title: "随行电力", description: "为远离插座的长日准备。", tag: "电池" }, { title: "整洁充电", description: "紧凑充电器和耐用线缆。", tag: "充电" }, { title: "合适保护", description: "保护屏幕、摄像头和手机壳。", tag: "护理" }, { title: "顺畅声音", description: "适合通话、专注和旅行的音频。", tag: "音频" }] },
    approach: { label: "Nexa 如何精选", title: "有用的科技，而非无尽的目录。", body: "我们按产品需要完成的任务整理推荐。", points: ["日常实用优先", "清晰的品类背景", "不使用虚构评分或折扣"], action: "浏览品类目录" },
    guide: { label: "购买前", title: "为你的日常选择，而非参数表。", body: "用指南将电源、保护、音频和连接方式匹配到你的真实一天。", action: "阅读购买指南" },
    footer: { tagline: "让每天手机使用更好的实用电子产品。", shop: "选购", company: "Nexa", legal: "法律", privacy: "隐私", terms: "条款", cookies: "Cookie", rights: "版权所有。" },
  },
};
