/** Editorial Tech Marketplace: transparent, filterable product discovery without fabricated catalog entries. */
import { useMemo, useState } from "react";
import { ArrowUpRight, Search, SlidersHorizontal, X } from "lucide-react";
import { catalogCategories, catalogProducts, type CatalogProduct, type ProductCategory } from "@/lib/catalog";
import type { LanguageCode } from "@/lib/i18n";

type ExplorerCopy = {
  eyebrow: string; title: string; body: string; search: string; searchPlaceholder: string; filters: string; price: string; min: string; max: string; sort: string; featured: string; low: string; high: string; clear: string; results: string; emptyTitle: string; emptyBody: string; categories: Record<ProductCategory, string>;
};

const copy: Record<LanguageCode, ExplorerCopy> = {
  en: { eyebrow: "Product finder", title: "Find the right fit, faster.", body: "Search verified product entries by use case, category, and price. The catalogue becomes available as approved affiliate products are added.", search: "Search", searchPlaceholder: "Search products", filters: "Filters", price: "Price range", min: "Min", max: "Max", sort: "Sort", featured: "Featured", low: "Price: low to high", high: "Price: high to low", clear: "Clear filters", results: "results", emptyTitle: "The verified catalogue is being prepared.", emptyBody: "Use the filters now; product cards appear here as Nexa adds approved products, verified prices, and affiliate links.", categories: { phones: "Phones", charging: "Charging", protection: "Protection", audio: "Audio", work: "Work & travel" } },
  ar: { eyebrow: "مستكشف المنتجات", title: "اعثر على الملاءمة المناسبة بسرعة.", body: "ابحث في المنتجات الموثقة حسب الاستخدام أو الفئة أو السعر. يصبح الكتالوج متاحاً مع إضافة منتجات العمولة المعتمدة.", search: "بحث", searchPlaceholder: "ابحث عن منتج", filters: "التصفية", price: "نطاق السعر", min: "الحد الأدنى", max: "الحد الأعلى", sort: "الترتيب", featured: "المميزة", low: "السعر: من الأقل للأعلى", high: "السعر: من الأعلى للأقل", clear: "مسح التصفية", results: "نتيجة", emptyTitle: "يجري تجهيز الكتالوج الموثق.", emptyBody: "استخدم الفلاتر الآن؛ ستظهر بطاقات المنتجات هنا عند إضافة Nexa للمنتجات المعتمدة والأسعار وروابط العمولة الموثقة.", categories: { phones: "الهواتف", charging: "الشحن", protection: "الحماية", audio: "الصوت", work: "العمل والسفر" } },
  es: { eyebrow: "Buscador de productos", title: "Encuentra la opción adecuada más rápido.", body: "Busca productos verificados por uso, categoría y precio. El catálogo estará disponible al añadir productos de afiliación aprobados.", search: "Buscar", searchPlaceholder: "Buscar productos", filters: "Filtros", price: "Rango de precio", min: "Mín.", max: "Máx.", sort: "Ordenar", featured: "Destacados", low: "Precio: menor a mayor", high: "Precio: mayor a menor", clear: "Limpiar filtros", results: "resultados", emptyTitle: "El catálogo verificado está en preparación.", emptyBody: "Usa los filtros ahora; las tarjetas aparecerán cuando Nexa añada productos aprobados, precios verificados y enlaces de afiliación.", categories: { phones: "Teléfonos", charging: "Carga", protection: "Protección", audio: "Audio", work: "Trabajo y viajes" } },
  fr: { eyebrow: "Recherche produit", title: "Trouvez le bon choix plus vite.", body: "Recherchez des produits vérifiés par usage, catégorie et prix. Le catalogue sera disponible lorsque les produits affiliés approuvés seront ajoutés.", search: "Rechercher", searchPlaceholder: "Rechercher des produits", filters: "Filtres", price: "Fourchette de prix", min: "Min.", max: "Max.", sort: "Trier", featured: "Sélection", low: "Prix croissant", high: "Prix décroissant", clear: "Effacer les filtres", results: "résultats", emptyTitle: "Le catalogue vérifié est en préparation.", emptyBody: "Utilisez les filtres dès maintenant ; les produits apparaîtront lorsque Nexa ajoutera des prix et liens affiliés vérifiés.", categories: { phones: "Téléphones", charging: "Charge", protection: "Protection", audio: "Audio", work: "Travail et voyage" } },
  de: { eyebrow: "Produktfinder", title: "Schneller die passende Wahl finden.", body: "Durchsuchen Sie geprüfte Produkte nach Einsatz, Kategorie und Preis. Der Katalog ist verfügbar, sobald genehmigte Affiliate-Produkte ergänzt werden.", search: "Suchen", searchPlaceholder: "Produkte suchen", filters: "Filter", price: "Preisspanne", min: "Min.", max: "Max.", sort: "Sortieren", featured: "Ausgewählt", low: "Preis: aufsteigend", high: "Preis: absteigend", clear: "Filter löschen", results: "Ergebnisse", emptyTitle: "Der geprüfte Katalog wird vorbereitet.", emptyBody: "Nutzen Sie die Filter bereits jetzt; Karten erscheinen, sobald Nexa geprüfte Produkte, Preise und Affiliate-Links ergänzt.", categories: { phones: "Telefone", charging: "Laden", protection: "Schutz", audio: "Audio", work: "Arbeit und Reise" } },
  pt: { eyebrow: "Localizador de produtos", title: "Encontre a opção certa mais rápido.", body: "Pesquise produtos verificados por uso, categoria e preço. O catálogo ficará disponível conforme produtos afiliados aprovados forem adicionados.", search: "Buscar", searchPlaceholder: "Buscar produtos", filters: "Filtros", price: "Faixa de preço", min: "Mín.", max: "Máx.", sort: "Ordenar", featured: "Destaques", low: "Preço: menor para maior", high: "Preço: maior para menor", clear: "Limpar filtros", results: "resultados", emptyTitle: "O catálogo verificado está sendo preparado.", emptyBody: "Use os filtros agora; os produtos aparecerão quando a Nexa adicionar produtos aprovados, preços verificados e links de afiliado.", categories: { phones: "Telefones", charging: "Carregamento", protection: "Proteção", audio: "Áudio", work: "Trabalho e viagem" } },
  ja: { eyebrow: "商品検索", title: "最適な選択をすばやく見つける。", body: "用途、カテゴリ、価格で確認済みの商品を検索できます。承認済みのアフィリエイト商品が追加されるとカタログが利用できます。", search: "検索", searchPlaceholder: "商品を検索", filters: "フィルター", price: "価格帯", min: "最低", max: "最高", sort: "並べ替え", featured: "おすすめ", low: "価格：安い順", high: "価格：高い順", clear: "フィルターをクリア", results: "件", emptyTitle: "確認済みカタログを準備中です。", emptyBody: "フィルターは今から使えます。Nexa が承認済み商品、確認済み価格、アフィリエイトリンクを追加すると商品カードが表示されます。", categories: { phones: "スマートフォン", charging: "充電", protection: "保護", audio: "オーディオ", work: "仕事と旅行" } },
  zh: { eyebrow: "产品查找器", title: "更快找到合适选择。", body: "按用途、类别和价格搜索已验证产品。添加已批准的联盟产品后即可使用目录。", search: "搜索", searchPlaceholder: "搜索产品", filters: "筛选", price: "价格范围", min: "最低", max: "最高", sort: "排序", featured: "精选", low: "价格：从低到高", high: "价格：从高到低", clear: "清除筛选", results: "个结果", emptyTitle: "已验证目录正在准备中。", emptyBody: "现在即可使用筛选器；Nexa 添加已批准产品、已验证价格和联盟链接后，产品卡片将显示在这里。", categories: { phones: "手机", charging: "充电", protection: "保护", audio: "音频", work: "工作与旅行" } },
};

export default function ProductExplorer({ language }: { language: LanguageCode }) {
  const text = copy[language];
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<ProductCategory[]>([]);
  const [minPrice, setMinPrice] = useState("");
  const [maxPrice, setMaxPrice] = useState("");
  const [sort, setSort] = useState<"featured" | "low" | "high">("featured");
  const min = Number(minPrice);
  const max = Number(maxPrice);
  const results = useMemo<CatalogProduct[]>(() => catalogProducts
    .filter((product: CatalogProduct) => !query || `${product.name} ${product.summary}`.toLowerCase().includes(query.toLowerCase()))
    .filter((product: CatalogProduct) => selected.length === 0 || selected.includes(product.category))
    .filter((product: CatalogProduct) => !minPrice || product.priceUsd >= min)
    .filter((product: CatalogProduct) => !maxPrice || product.priceUsd <= max)
    .sort((a: CatalogProduct, b: CatalogProduct) => sort === "low" ? a.priceUsd - b.priceUsd : sort === "high" ? b.priceUsd - a.priceUsd : 0), [max, maxPrice, min, minPrice, query, selected, sort]);

  const toggleCategory = (category: ProductCategory) => setSelected((current) => current.includes(category) ? current.filter((item) => item !== category) : [...current, category]);
  const clear = () => { setQuery(""); setSelected([]); setMinPrice(""); setMaxPrice(""); setSort("featured"); };

  return <section id="product-finder" className="border-y border-[#DDD9D2] bg-white">
    <div className="container py-16 sm:py-20">
      <div className="grid gap-7 border-b border-[#DDD9D2] pb-10 lg:grid-cols-[0.75fr_1.25fr] lg:items-end lg:gap-16">
        <div><p className="text-[11px] font-extrabold uppercase tracking-[0.18em] text-[#C9141B]">{text.eyebrow}</p><h2 className="mt-4 text-[clamp(2.1rem,4vw,4rem)] font-extrabold leading-[1] tracking-[-0.06em]">{text.title}</h2></div>
        <p className="max-w-2xl text-[16px] font-medium leading-8 text-[#66676B]">{text.body}</p>
      </div>

      <div className="grid gap-8 py-8 lg:grid-cols-[280px_1fr] lg:gap-12">
        <aside className="h-fit border-y border-[#DDD9D2] lg:sticky lg:top-24">
          <div className="border-b border-[#DDD9D2] py-5"><p className="text-[11px] font-extrabold uppercase tracking-[0.15em] text-[#C9141B]">{text.filters}</p><div className="mt-4 flex flex-wrap gap-2">{catalogCategories.map((category: ProductCategory) => <button type="button" key={category} onClick={() => toggleCategory(category)} aria-pressed={selected.includes(category)} className={`border px-3 py-2 text-xs font-extrabold transition-colors ${selected.includes(category) ? "border-[#0A0A0A] bg-[#0A0A0A] text-white" : "border-[#DDD9D2] bg-[#F7F5F2] hover:border-[#C9141B]"}`}>{text.categories[category]}</button>)}</div></div>
          <div className="border-b border-[#DDD9D2] py-5"><p className="text-[11px] font-extrabold uppercase tracking-[0.15em] text-[#C9141B]">{text.price} (USD)</p><div className="mt-4 grid grid-cols-2 gap-3"><input type="number" min="0" inputMode="decimal" value={minPrice} onChange={(event) => setMinPrice(event.target.value)} placeholder={text.min} aria-label={text.min} className="h-11 w-full border border-[#DDD9D2] bg-white px-3 text-sm font-bold outline-none ring-[#C9141B] focus:ring-1" /><input type="number" min="0" inputMode="decimal" value={maxPrice} onChange={(event) => setMaxPrice(event.target.value)} placeholder={text.max} aria-label={text.max} className="h-11 w-full border border-[#DDD9D2] bg-white px-3 text-sm font-bold outline-none ring-[#C9141B] focus:ring-1" /></div></div>
          <button type="button" onClick={clear} className="flex w-full items-center justify-between py-4 text-xs font-extrabold text-[#66676B] transition-colors hover:text-[#C9141B]"><span>{text.clear}</span><X className="h-4 w-4" /></button>
        </aside>

        <div>
          <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><label className="flex h-12 flex-1 items-center gap-3 border border-[#0A0A0A] bg-[#F7F5F2] px-4 sm:max-w-[460px]"><Search className="h-4 w-4 text-[#C9141B]" /><span className="sr-only">{text.search}</span><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={text.searchPlaceholder} className="w-full bg-transparent text-sm font-semibold outline-none placeholder:text-[#8D8D91]" /></label><label className="flex h-12 items-center gap-3 border border-[#DDD9D2] bg-white px-3 text-sm font-bold"><SlidersHorizontal className="h-4 w-4 text-[#C9141B]" /><span className="sr-only">{text.sort}</span><select value={sort} onChange={(event) => setSort(event.target.value as typeof sort)} className="bg-transparent text-sm outline-none"><option value="featured">{text.featured}</option><option value="low">{text.low}</option><option value="high">{text.high}</option></select></label></div>
          <div className="mt-5 flex items-center justify-between border-b border-[#DDD9D2] pb-4 text-xs font-extrabold uppercase tracking-[0.13em] text-[#66676B]"><span>{results.length} {text.results}</span><span>VERIFIED LINKS ONLY</span></div>
          {results.length > 0 ? <div className="mt-6 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{results.map((product: CatalogProduct) => <article key={product.id} className="border border-[#DDD9D2] bg-[#F7F5F2] p-4"><img src={product.imageUrl} alt="" className="aspect-square w-full border border-[#DDD9D2] bg-white object-contain" /><p className="mt-4 text-[10px] font-extrabold uppercase tracking-[0.15em] text-[#C9141B]">{text.categories[product.category]}</p><h3 className="mt-2 text-lg font-extrabold tracking-[-0.04em]">{product.name}</h3><p className="mt-2 text-sm font-medium leading-6 text-[#66676B]">{product.summary}</p><div className="mt-5 flex items-center justify-between border-t border-[#DDD9D2] pt-4"><span className="text-sm font-extrabold">${product.priceUsd}</span><a href={product.affiliateUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 text-xs font-extrabold text-[#C9141B]">SHOP <ArrowUpRight className="h-4 w-4" /></a></div></article>)}</div> : <div className="mt-6 border border-dashed border-[#C9141B]/45 bg-[#C9141B]/[0.035] p-8 sm:p-10"><p className="text-[11px] font-extrabold uppercase tracking-[0.16em] text-[#C9141B]">NEXA / CATALOGUE STATUS</p><h3 className="mt-4 text-2xl font-extrabold tracking-[-0.045em]">{text.emptyTitle}</h3><p className="mt-4 max-w-2xl text-[15px] font-medium leading-7 text-[#66676B]">{text.emptyBody}</p></div>}
        </div>
      </div>
    </div>
  </section>;
}
